# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-04 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0005_auto_20171204_0723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=256, verbose_name='resource name')),
                ('rtype', models.IntegerField(choices=[(0, 'file'), (1, 'folder')], verbose_name='file or folder')),
                ('description', models.CharField(max_length=1024, verbose_name='description in Markdown')),
                ('avatar', models.URLField(blank=True, default=None, null=True)),
                ('dlpath', models.CharField(default=None, max_length=1024, verbose_name='download relative path to res.6-79.cn')),
                ('status', models.IntegerField(choices=[(0, 'public'), (1, 'private'), (2, 'protect')], default=0, verbose_name='加密状态 0公开 1仅自己可见 2需要密码')),
                ('visit_key', models.CharField(max_length=4, verbose_name='当status为2时有效')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.User')),
                ('parent', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='Resource.Resource')),
            ],
        ),
    ]
