# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-04 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='rsize',
            field=models.IntegerField(default=0),
        ),
    ]
