# Generated by Django 2.0 on 2017-12-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resource', '0002_resource_rsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='create_time',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
