# Generated by Django 2.0 on 2017-12-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resource', '0003_resource_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='dlpath',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True, verbose_name='download relative path to res.6-79.cn'),
        ),
    ]
