# Generated by Django 2.0 on 2018-01-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resource', '0005_auto_20171216_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='dlcount',
            field=models.IntegerField(default=0, verbose_name='download number'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='rtype',
            field=models.IntegerField(choices=[(0, 'file'), (1, 'folder'), (2, 'link')], verbose_name='file or folder'),
        ),
    ]
