# Generated by Django 2.0 on 2018-01-11 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resource', '0006_auto_20180110_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='sub_type',
            field=models.IntegerField(choices=[(0, 'folder'), (1, 'image'), (2, 'video'), (3, 'music'), (4, 'normal file'), (5, 'link')], default=0, verbose_name='sub type'),
        ),
    ]
