# Generated by Django 2.0 on 2018-01-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resource', '0009_auto_20180122_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='create_time',
            field=models.DateTimeField(),
        ),
    ]
