# Generated by Django 2.0 on 2018-02-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resource', '0010_auto_20180122_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='res_str_id',
            field=models.CharField(blank=True, default=None, max_length=6, null=True, unique=True, verbose_name='唯一随机资源ID，弃用res_id'),
        ),
    ]
