# Generated by Django 2.0 on 2018-02-14 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_auto_20171216_2135'),
        ('Resource', '0011_resource_res_str_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verify_time', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='vk_change_time',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='userright',
            name='res',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resource.Resource'),
        ),
        migrations.AddField(
            model_name='userright',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.User'),
        ),
    ]
