# Generated by Django 2.0 on 2018-02-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resource', '0012_auto_20180214_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='right_bubble',
            field=models.NullBooleanField(default=True, verbose_name='读取权限向上冒泡'),
        ),
    ]
