# Generated by Django 2.0 on 2018-02-17 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resource', '0013_resource_right_bubble'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='visit_key',
            field=models.CharField(max_length=16, verbose_name='当status为2时有效'),
        ),
    ]
