# Generated by Django 2.0 on 2018-11-28 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resource', '0014_auto_20180217_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='cover_type',
            field=models.IntegerField(blank=0, choices=[(0, 'upload cover'), (1, 'same as parent'), (2, 'use outsize link')], default=0, null=0, verbose_name='封面类型 0 上传图片 1 与父资源相同 2 与指定资源相同 3 外部URI链接'),
        ),
    ]
