# Generated by Django 5.0.3 on 2024-03-27 15:29

import SmartDjango.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resource', '0015_resource_cover_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='userright',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='resource',
            name='mime',
            field=SmartDjango.models.fields.CharField(default=True, max_length=100, null=True, verbose_name='资源类型'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='cover',
            field=SmartDjango.models.fields.CharField(blank=True, default=None, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='cover_type',
            field=SmartDjango.models.fields.IntegerField(blank=0, choices=[(0, 'RANDOM'), (1, 'UPLOAD'), (2, 'PARENT'), (3, 'OUTLNK'), (4, 'SELF'), (5, 'RESOURCE')], default=0, null=0, verbose_name='封面类型 0 上传图片 1 与父资源相同 2 与指定资源相同 3 外部URI链接'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='create_time',
            field=SmartDjango.models.fields.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='description in Markdown'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='dlcount',
            field=SmartDjango.models.fields.IntegerField(default=0, verbose_name='download number'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='dlpath',
            field=SmartDjango.models.fields.CharField(blank=True, default=None, max_length=1024, null=True, verbose_name='download relative path to res.6-79.cn'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='res_str_id',
            field=SmartDjango.models.fields.CharField(blank=True, default=None, max_length=6, null=True, unique=True, verbose_name='唯一随机资源ID，弃用res_id'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='right_bubble',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='读取权限向上冒泡'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='rname',
            field=SmartDjango.models.fields.CharField(max_length=256, verbose_name='resource name'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='rsize',
            field=SmartDjango.models.fields.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resource',
            name='rtype',
            field=SmartDjango.models.fields.IntegerField(choices=[(0, 'FILE'), (1, 'FOLDER'), (2, 'LINK')], verbose_name='file or folder'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='status',
            field=SmartDjango.models.fields.IntegerField(choices=[(0, 'PUBLIC'), (1, 'PRIVATE'), (2, 'PROTECT')], default=0, verbose_name='加密状态 0公开 1仅自己可见 2需要密码'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='sub_type',
            field=SmartDjango.models.fields.IntegerField(choices=[(0, 'FOLDER'), (1, 'IMAGE'), (2, 'VIDEO'), (3, 'MUSIC'), (4, 'FILE'), (5, 'LINK')], default=0, verbose_name='sub type'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='visit_key',
            field=SmartDjango.models.fields.CharField(max_length=16, verbose_name='当status为2时有效'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='vk_change_time',
            field=SmartDjango.models.fields.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userright',
            name='verify_time',
            field=SmartDjango.models.fields.FloatField(default=0),
        ),
    ]
