# Generated by Django 5.0.3 on 2024-03-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0002_auto_20180222_2022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterField(
            model_name='config',
            name='key',
            field=models.fields.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='value',
            field=models.fields.CharField(max_length=255),
        ),
    ]
