# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-02 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='hash_password',
            new_name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='grant',
            field=models.BooleanField(default=False, verbose_name='whether have right to create user'),
        ),
    ]
