# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-14 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20171204_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
