# Generated by Django 2.0 on 2017-12-16 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='User.User'),
        ),
    ]
