# Generated by Django 2.0 on 2017-12-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_auto_20171216_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pwd_change_time',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
