# Generated by Django 2.0 on 2017-12-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_user_pwd_change_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True),
        ),
    ]
