# Generated by Django 2.0 on 2018-04-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_auto_20180422_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pwd_change_time',
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
