# Generated by Django 5.0.3 on 2024-03-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_auto_20180423_0409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.fields.CharField(blank=True, default=None, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.fields.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.fields.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='qt_user_app_id',
            field=models.fields.CharField(default=None, max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='qtb_token',
            field=models.fields.CharField(default=None, max_length=256),
        ),
    ]
