# Generated by Django 5.2.4 on 2026-07-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_auto_20191003_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_sync_time',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
